name: test5
favicon: null
layout_spectrum: 0.2407898404635489
typography_spectrum: 0.48699162574484944
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.39232004899531603
  lightness: 0.6406040850561112
  saturation: 0.02644828543998301
  rhythmicContrast: 0.9522167225368321
purpose: []
